name: build
run-name: Build project
on: [push, pull_request]
jobs:
  Build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies 
        run: |
          cd utility/ && sudo ./install-oatpp-modules.sh && cd ..
          sudo apt update && sudo apt dist-upgrade -y
          sudo apt-get install libboost-all-dev libssl-dev -y
          git submodule update --init --recursive
      - name: Build project
        run: mkdir build && cd build && cmake .. && make
      - name: Run tests
        run: cd build && sudo ./license_consumer-test